version: "3"
services:
  app:
    build:
      context: .
      dockerfile: builds/Dockerfile
    container_name: app
    restart: always
    depends_on:
      - db
    volumes:
      - .:/work_dir
    env_file:
      - .envs/.fast_api
      - .envs/.mysql
    # networks:
    #   - fastapi_network
    # command: uvicorn app.api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: bash -c "../scripts/run.sh"
    ports:
      - 8000:8000
  db:
    image: mysql:5.7
    container_name: db
    # restart: always
    # tty: true
    # networks:
    #   - fastapi_network
    env_file:
      - .envs/.mysql
    # volumes:
    #   - ./app:/wark_dir/app:cached
    #   - ./db:/wark_dir/db:cached
    #   - ./scripts:/wark_dir/scripts:cached
    ports:
      - "3306:3306"
    # command: "touch /var/log/mysql/mysqld.log"
volumes:
  mysql_data:

# networks:
#   default:
#     external:
#       name: bridge
#   fastapi_network:
#     name: fastapi_network
#     driver: bridge
#     external: true
